'use client';

import React from 'react';
import {
  ShieldCheck,
  CheckCircle2,
  Lock,
  FileCode,
  Terminal,
  ExternalLink,
  Layers,
  Sparkles,
} from 'lucide-react';

interface FooterProps {
  onOpenGovernanceDrawer?: () => void;
  onOpenLogsDrawer?: () => void;
  onOpenChaosModal?: () => void;
}

export function Footer({
  onOpenGovernanceDrawer,
  onOpenLogsDrawer,
  onOpenChaosModal,
}: FooterProps) {
  return (
    <footer className="w-full border-t border-[var(--color-border)] bg-[var(--color-panel-subtle)] py-12 text-[var(--color-text-secondary)]">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 space-y-10">
        {/* Top 3-Column Architectural Decoupling & Governance Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Card 1: Air-Gapped Ingestion Boundary */}
          <div className="p-5 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] space-y-3 shadow-xs">
            <div className="flex items-center gap-2 text-[var(--color-text-primary)] font-bold text-sm">
              <div className="p-1.5 rounded-md bg-amber-500/10 text-amber-600 dark:text-amber-400">
                <Lock className="h-4 w-4" />
              </div>
              <span>Air-Gapped Ingestion Boundary</span>
            </div>
            <p className="text-xs leading-relaxed text-[var(--color-text-muted)]">
              Raw sales records from Instantly, Apollo, and Monday CRM are intercepted at the webhook boundary. They reside in an encrypted quarantine buffer and cannot sync to ChatGPT Business Company Knowledge without automated NER scrubbing and senior human approval.
            </p>
            <div className="pt-1 flex items-center gap-2 text-xs font-mono font-semibold text-amber-800 dark:text-amber-400">
              <span className="h-2 w-2 rounded-full bg-amber-500 animate-pulse" />
              <span>Zero-Leak Guarantee: 100% Enforced</span>
            </div>
          </div>

          {/* Card 2: Grounded ChatGPT Business Retrieval */}
          <div className="p-5 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] space-y-3 shadow-xs">
            <div className="flex items-center gap-2 text-[var(--color-text-primary)] font-bold text-sm">
              <div className="p-1.5 rounded-md bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
                <CheckCircle2 className="h-4 w-4" />
              </div>
              <span>Deterministic DocID Attribution</span>
            </div>
            <p className="text-xs leading-relaxed text-[var(--color-text-muted)]">
              Every enterprise answer generated by ChatGPT Business Company Knowledge is grounded strictly in approved, version-controlled records from the Wix/Algolia Public Library and Monday SOPs, citing exact canonical <code className="text-xs bg-slate-100 dark:bg-slate-800 px-1 py-0.5 rounded font-mono">[DocID]</code> identifiers.
            </p>
            <div className="pt-1 flex items-center gap-2 text-xs font-mono font-semibold text-emerald-700 dark:text-emerald-400">
              <span className="h-2 w-2 rounded-full bg-emerald-500" />
              <span>Hallucination Bound: Grounded Retrieval</span>
            </div>
          </div>

          {/* Card 3: Enterprise AI Governance Standard */}
          <div className="p-5 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] space-y-3 shadow-xs">
            <div className="flex items-center gap-2 text-[var(--color-text-primary)] font-bold text-sm">
              <div className="p-1.5 rounded-md bg-indigo-500/10 text-indigo-600 dark:text-indigo-400">
                <ShieldCheck className="h-4 w-4" />
              </div>
              <span>Securiti Certified AI Architecture</span>
            </div>
            <p className="text-xs leading-relaxed text-[var(--color-text-muted)]">
              Architected in accordance with NIST AI Risk Management Framework (AI RMF 1.0) and OWASP Top 10 for LLMs. Features automated PII scrubbing (LLM02), strict prompt isolation (LLM01), and dual-provider failover routing (OpenAI & Google Gemini).
            </p>
            <div className="pt-1 flex items-center gap-2 text-xs font-mono font-semibold text-indigo-700 dark:text-indigo-400">
              <span className="h-2 w-2 rounded-full bg-indigo-500" />
              <span>Cert ID: 14B411BCE-14B411A3D</span>
            </div>
          </div>
        </div>

        {/* Middle Interactive Diagnostics & Technical Quick Links */}
        <div className="pt-6 border-t border-[var(--color-border)] flex flex-wrap items-center justify-between gap-4 text-xs">
          <div className="flex items-center gap-4">
            <button
              onClick={onOpenGovernanceDrawer}
              className="inline-flex items-center gap-1.5 hover:text-[var(--color-text-primary)] transition-colors font-medium"
            >
              <ShieldCheck className="h-3.5 w-3.5 text-emerald-600 dark:text-emerald-400" />
              <span>NIST AI Governance Drawer</span>
            </button>
            <button
              onClick={onOpenLogsDrawer}
              className="inline-flex items-center gap-1.5 hover:text-[var(--color-text-primary)] transition-colors font-medium"
            >
              <Terminal className="h-3.5 w-3.5 text-indigo-500" />
              <span>Live Ingestion Telemetry</span>
            </button>
            <button
              onClick={onOpenChaosModal}
              className="inline-flex items-center gap-1.5 hover:text-[var(--color-text-primary)] transition-colors font-medium"
            >
              <Layers className="h-3.5 w-3.5 text-amber-600 dark:text-amber-400" />
              <span>Boundary Interception Tests</span>
            </button>
          </div>

          <div className="flex items-center gap-3 font-mono text-xs text-[var(--color-text-muted)]">
            <span>Next.js 15.5 App Router</span>
            <span>•</span>
            <span>Fluid Compute</span>
            <span>•</span>
            <span>Velo + Zapier Webhooks</span>
          </div>
        </div>

        {/* Bottom Baseline Bar */}
        <div className="pt-6 border-t border-[var(--color-border)] flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-[var(--color-text-muted)]">
          <div className="flex items-center gap-2">
            <span className="font-bold text-[var(--color-text-primary)]">Forward AR Core</span>
            <span>—</span>
            <span>Governed RAG & Knowledge Systems Architecture</span>
          </div>
          <div className="flex items-center gap-2">
            <span>Engineered by</span>
            <span className="font-medium text-[var(--color-text-primary)]">BarakahSoft Systems Architecture</span>
            <span>(12+ Years Enterprise Systems)</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
